### ISSUE TITLE
只消耗token,没有任何返回[Bug] 

### ISSUE THREAD

**Issue by SeqCrafter** [lobehub/chat-plugin-web-crawler#4]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

调用插件，然后只是消耗大量的token,没有任何返回信息，或者无效返回信息

### 📷 复现步骤 | Recurrence Steps

提问“搜索eccDNA的最新发现”，调用gpt-4-32k模型，输入28981提示词，消耗3$额度，返回为“无法提供“。
提问”搜索GeminiPro的最新消息“，调用gpt-4-1106-preview, 输入29052和29498提示词，消耗2$额度，返回为空

**Comment by arvinxx** [comment]
能否给出更进一步的信息。比如会话上下文？正常情况下不太可能一轮对话直接消耗3w token的

**Comment by SeqCrafter** [comment]
![LobeChat_随便聊聊_2023-12-26](https://github.com/lobehub/chat-plugin-web-crawler/assets/43256809/1bcb0881-2ce9-46e2-93e7-2e98839bc35c)
就没有任何其他的信息
<img width="1096" alt="截屏2023-12-26 11 57 02" src="https://github.com/lobehub/chat-plugin-web-crawler/assets/43256809/986ac0e9-bab4-4427-9302-36a23dc1b437">

**Comment by arvinxx** [comment]
第一个网页爬虫插件返回的内容超出token限制了。

**Comment by SeqCrafter** [comment]
> 第一个网页爬虫插件返回的内容超出token限制了。

第一个调用的gpt-3.5,因为超出限制，所以我试用了gpt-4-32k, 然后就大量消耗
