### ISSUE TITLE
[Bug] 页面内容太长会报错

### ISSUE THREAD

**Issue by mushan0x0** [lobehub/chat-plugin-web-crawler#5]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

希望可以根据当前剩余token来限制读取内容的长度

### 📷 复现步骤 | Recurrence Steps

<img width="183" alt="image" src="https://github.com/lobehub/chat-plugin-web-crawler/assets/29084441/13760e07-44ac-4b2d-afd1-d7f656107828">

**Comment by arvinxx** [comment]
这个感觉不太好做，剩余 token 是应用层面的信息，会话上下文如何感知？

**Comment by mushan0x0** [comment]
> 这个感觉不太好做，剩余 token 是应用层面的信息，会话上下文如何感知？

跟应用层通信的时候或许可以暴露一些上下文参数，这样插件在运行时可以进行一些判断

**Comment by arvinxx** [comment]
> 跟应用层通信的时候或许可以暴露一些上下文参数，这样插件在运行时可以进行一些判断

如果是这种，倒是可以

**Comment by arvinxx** [comment]
目前看下来现在模型长度已经不是问题了
