### ISSUE TITLE
[Bug] 经常报错未收到上游服务器响应

### ISSUE THREAD

**Issue by Yerosius** [lobehub/chat-plugin-web-crawler#7]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

如题，访问https://web-crawler.chat-plugin.lobehub.com/api/v1页面会显示500错误-This Serverless Function has crashed.
![image](https://github.com/lobehub/chat-plugin-web-crawler/assets/76488510/9b56e7c9-f8c7-49c0-ae7a-c06f6672dbcd)

**Comment by arvinxx** [comment]
直接访问当然不支持了…
